name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: 'Build, Test, and Push'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2-alpine3.19
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pass-in-db-temp
        options: >-
          --health-cmd="pg_isready -U postgres 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }} .

    - name: Run Tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pass-in-db-temp
      run: |
        pnpm test

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }}
        docker tag leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }} leonardohentschke/service-passin:latest
        docker push leonardohentschke/service-passin:latest
