name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: 'Build, test and push'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2-alpine3.19
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: pass-in-db
        options: --health-cmd="pg_isready -U admin -d pass-in-db" --health-interval=10s

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }} .

    - name: Run Tests
      run: |
        docker-compose -f docker-compose.yml up -d
        # Aguardando o serviço estar pronto, se necessário
        sleep 20
        # Instalar dependências e rodar os testes
        docker-compose -f docker-compose.yml run --rm api-pass-in npm install
        docker-compose -f docker-compose.yml run --rm api-pass-in npm test
        docker-compose -f docker-compose.yml down

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }}
        docker tag leonardohentschke/service-passin:${{ steps.generate_sha.outputs.sha }} leonardohentschke/service-passin:latest
        docker push leonardohentschke/service-passin:latest
